" Vimrc
" Eric Moss
"

"""""""""""""""
" INDENTATION "
"""""""""""""""
" change tabs to instead be 4 spaces
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab


""""""""""
" VISUAL "
""""""""""

" Line numbering
set number
set relativenumber
" Syntax highlighting
syntax on
