" Vimrc
" Eric Moss
"

"""""""""""""""
" INDENTATION "
"""""""""""""""
" change tabs to instead be 4 spaces
set shiftwidth=4
set softtabstop=4
set expandtab
set smarttab
" autoindentation
set ai


""""""""""
" VISUAL "
""""""""""

" Line numbering
set number
set relativenumber
" show current line and number
set ruler
" Syntax highlighting
syntax on
