# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd beep extendedglob notify
unsetopt nomatch
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/eric/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

###########
# ALIASES #
###########

# shorten frequently used commands
alias la='ls -A'
alias ll='ls -lh'	# -h makes sizes human readable
alias lla='ls -lAh'
alias cl=clear

# simple pingtest to cloudflare's dns server
alias pingtest='ping 1.1.1.1'

# aliases for easy modification to dotfiles
alias zshrc='vim ~/.zshrc && source ~/.zshrc'
alias i3config='vim ~/.config/i3/config && i3-msg reload && i3-msg restart'
alias vimrc='vim ~/.vimrc'

# enable "fuck" command if installed
if [ thefuck ]; then
	eval $(thefuck --alias)
fi

# start tmux when running in terminal emulator
if [ ! $TERM =~ screen ] && [ ! $TERM =~ linux ]; then
	exec tmux
fi
